import Header from "@/components/Header"
import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>2048</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-orange-50 h-screen w-screen flex flex-col items-center">
        <Header />
        {/* logic context? */}
        {/* header */}
        {/* board */}
      </main>
    </>
  )
}
